{{- range $key, $spec := .Values }}
{{- if or (eq $key "policy") (eq $key "telemetry") }}
{{- if and $spec.enabled $spec.autoscaleEnabled $spec.autoscaleMin $spec.autoscaleMax }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "mixer.name" $ }}
    chart: {{ template "mixer.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
spec:
    maxReplicas: {{ $spec.autoscaleMax }}
    minReplicas: {{ $spec.autoscaleMin }}
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: istio-{{ $key }}
    metrics:
    - resource:
        name: cpu
        target: 
           averageUtilization: {{ $spec.cpu.targetAverageUtilization }}
           type: Utilization
    - resource:
        name: memory
        target:
          averageUtilization: {{ $spec.memory.targetAverageUtilization }}
          type: Utilization
    type: Resource
---
{{- end }}
{{- end }}
{{- end }}
