{{- if and .Values.autoscaleEnabled .Values.autoscaleMin .Values.autoscaleMax }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: istio-pilot
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "pilot.name" . }}
    chart: {{ template "pilot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.autoscaleMax }}
  minReplicas: {{ .Values.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: istio-pilot
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: {{ .Values.cpu.targetAverageUtilization }}
        type: Utilization
  - resource:
      name: memory
      target:
        averageUtilization: {{ .Values.memory.targetAverageUtilization }}
        type: Utilization
    type: Resource
---
{{- end }}
